"use client";

const MOCK_ACTIONS = [
  { title: "Complete HW 3 on Gradescope", priority: 1, due_date: "2026-04-02", rationale: "Due in 5 days — highest weighted assignment this week." },
  { title: "Review dynamic programming notes", priority: 2, due_date: null, rationale: "Exam next week. Weak coverage in your study materials." },
  { title: "Connect Edfinity to capture problem set deadlines", priority: 3, due_date: null, rationale: "Edfinity was detected in syllabus but not yet connected." },
  { title: "Midterm 2 — prepare", priority: 4, due_date: "2026-04-10", rationale: "Worth 25% of grade. Currently at risk based on category performance." },
];

const priorityColors = ["bg-red-100 border-red-300", "bg-orange-50 border-orange-200", "bg-yellow-50 border-yellow-200", "bg-gray-50 border-gray-200"];

export default function ActionBoardPage() {
  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold">Action Board</h1>
          <p className="text-sm text-gray-500 mt-1">Generated by Judgment Agent · Updated now</p>
        </div>
        <span className="px-3 py-1 text-xs font-semibold rounded-full bg-orange-500 text-white">Medium Risk</span>
      </div>

      <div className="border rounded-xl p-4 bg-yellow-50 border-yellow-200 text-sm text-yellow-900">
        <strong>Focus this week:</strong> HW 3 is your most urgent item. After that, start Midterm 2 prep — it carries 25% of your grade.
      </div>

      <div className="space-y-3">
        {MOCK_ACTIONS.map((action, i) => (
          <div key={i} className={`border rounded-xl p-4 ${priorityColors[i] ?? "bg-white border-gray-200"}`}>
            <div className="flex items-start justify-between gap-3">
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <span className="text-xs font-bold text-gray-400">#{action.priority}</span>
                  <p className="font-semibold text-sm">{action.title}</p>
                </div>
                <p className="text-xs text-gray-600">{action.rationale}</p>
              </div>
              {action.due_date && (
                <span className="shrink-0 text-xs text-gray-500">Due {action.due_date}</span>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
